### ISSUE TITLE
invalid string: invalid string: invalid whitespace

### ISSUE THREAD

**Issue by magick93** [hofstadter-io/cuetorials.com#26]
Hello

I'm trying to gently modify the basic cue example, but often get the below .

The command I'm running is `cue cmd -t "name=bob" gen-todos`

```
gen.templates.contents: invalid string: invalid string: invalid whitespace:
    ./first.cue:27:14
```

This error comes up when modifying what should be considered plain text, within `"""`.

For example:

```
contents: """
			
			{{ range $T := .I -}}
			
			model {{ $T.name }} {
				id	      Int      @id @default(autoincrement())
				createdAt DateTime @default(now())
                published Boolean  @default(true)			
			}
			{{ end }}
			"""
```

Oddly, the following code does NOT error:

```
contents: """
			
			{{ range $T := .I -}}
			
			model {{ $T.name }} {
				id	      Int      @id @default(autoincrement())
				createdAt DateTime @default(now())		
			}
			{{ end }}
			"""
```

**Comment by verdverm** [comment]
The whitespace does look off, in particular the `published...` line. If you look at the example code here (https://github.com/hofstadter-io/cuetorials.com/blob/main/code/first-steps/generate-all-the-things/first.cue#L25) note how the content is aligned to the left. It looks like your code may not be indented enough.

If the issue persists, could you make a reproducer following these guidelines? https://github.com/cuelang/cue/wiki/Creating-test-or-performance-reproducers

**Comment by magick93** [comment]
Thanks for the prompt reply.

I havent been able to reproduce this unfortunately. So I'll close this.

**Comment by magick93** [comment]
But I have one question:

> The whitespace does look off, in particular the published... line.

Shouldnt everything between the `"""` be excluding from any kind of linting of structural validation? Am I correct its essentially a text template with dynamic content between the curly brackets?

**Comment by verdverm** [comment]
Yes, except the left barrier is aligned with the """ so you can't unindent all the way to the left, as I understand it. CUE is still evolving and i haven't tried breaking this myself lately.
