### ISSUE TITLE
Question - How do you encode to JSON from evaluated cue value?

### ISSUE THREAD

**Issue by abhaybhargav** [hofstadter-io/cuetorials.com#33]
Hi 👋

Thanks very much for this tutorial repo. Really useful for implementing cue's features, with Go. 

I have a (probably) basic question. I have been able to load and evaluate a cue value. How do I encode it to JSON? I am unable to find specific references to this in cue's source as well. I am sure I am missing something. 

Any help would be highly appreciated. Thank you :)

**Comment by verdverm** [comment]
Hi @abhaybhargav, glad you find Cuetorials helpful.

You can use, copy, or reference the following function (and those that come after) (https://github.com/hofstadter-io/cuetils/blob/main/structural/output.go#L115) These are essentially the same calls that CUE makes when using the CLI.

Note, there are some inconsistencies in how CUE encodes values that will hopefully be rectified in time. In particular YAML uses the AST and JSON uses the ADT, which has more detail and context.

I should be adding a section about this under the `go-api/replicating-the-cli` sometime soon. Need to show how to load CUE like the `cue` CLI first, which requires some temp workaround (details here: https://github.com/hofstadter-io/hof/issues/22#issuecomment-998468995)

**Comment by abhaybhargav** [comment]
Please ignore this question. I found the `MarshalJSON()` function. I hadnt looked enough. Thanks :)
