### ISSUE TITLE
Translation work

### ISSUE THREAD

**Issue by h1z3y3** [hofstadter-io/cuetorials.com#35]
Any plan to translation? I'd like to contribute

**Comment by verdverm** [comment]
@h1z3y3 That's awesome, it should not be overly difficult to add. Hugo has good support for this.

Let me see about getting that set up, it likely requires moving all of the existing pages into a `en/` dir. We'll also want to add a language selector somewhere. Assuming this will be the Chinese translation under `cn/`. I've also wondered if it makes sense to host the Chinese version closer or in country to improve load times, but I don't know if they are good or bad.

It could be easier to coordinate if you join [Hof Slack](https://join.slack.com/t/hofstadter-io/shared_invite/zt-e5f90lmq-u695eJur0zE~AG~njNlT1A). Maybe we can do a video call to kick things off!
