### ISSUE TITLE
Chinese Edition

### ISSUE THREAD

**Issue by h1z3y3** [hofstadter-io/cuetorials.com#40]
These are all the path of the site.
If you want to contribute in Chinese translation work, please claim one of them and pull request all the pages under the one.

- [x] Introduction https://github.com/hofstadter-io/cuetorials.com/pull/36
- [x] Overview https://github.com/hofstadter-io/cuetorials.com/pull/38
- [x] First Step https://github.com/hofstadter-io/cuetorials.com/pull/39
- [x] Useful pattern https://github.com/hofstadter-io/cuetorials.com/pull/42
- [x] Deep Dive https://github.com/hofstadter-io/cuetorials.com/pull/44
    - [x] code-gen  https://github.com/hofstadter-io/cuetorials.com/pull/44
    - [x] packages  https://github.com/hofstadter-io/cuetorials.com/pull/44
- [x] The Go API
    - [x] atrribute https://github.com/hofstadter-io/cuetorials.com/pull/41
    - [x] basics https://github.com/hofstadter-io/cuetorials.com/pull/41
    - [x] loading https://github.com/hofstadter-io/cuetorials.com/pull/41
    - [x] replicating https://github.com/hofstadter-io/cuetorials.com/pull/41
    - [x] workflows https://github.com/hofstadter-io/cuetorials.com/pull/49
- [x] Walkthroughs https://github.com/hofstadter-io/cuetorials.com/pull/48
- [x] Cueology https://github.com/hofstadter-io/cuetorials.com/pull/45
    - [x] futurology https://github.com/hofstadter-io/cuetorials.com/pull/45
    - [x] internals https://github.com/hofstadter-io/cuetorials.com/pull/45
    - [x] known-issues https://github.com/hofstadter-io/cuetorials.com/pull/36
    - [x] theory https://github.com/hofstadter-io/cuetorials.com/pull/36
- [x] Miscellaneous https://github.com/hofstadter-io/cuetorials.com/pull/44
- [x] Videos https://github.com/hofstadter-io/cuetorials.com/pull/39
- [x] Jobs https://github.com/hofstadter-io/cuetorials.com/pull/36
- [x] Getting Help https://github.com/hofstadter-io/cuetorials.com/pull/36

**Comment by chivalryq** [comment]
May I take the "The Go API/*" part?

**Comment by h1z3y3** [comment]
> May I take the "The Go API/*" part?

Sure ! Thank you for taking the initiative here!

**Comment by chivalryq** [comment]
Got it.

**Comment by verdverm** [comment]
We should add a task for a contributors page, probably at the top level / last menu item.

**Comment by verdverm** [comment]
Made a PR for it #46
