### ISSUE TITLE
Font(s) not loading

### ISSUE THREAD

**Issue by slafs** [hofstadter-io/cuetorials.com#54]
For some time now my browsers started to reject loading the truetype font embedded on the site.

On Chrome I get this error in the console:

> Refused to load the font 'data:font/truetype;charset=utf-8;base64,d09GRgABAAAAAL...' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

The site looks like this:
<img width="1406" alt="Screenshot 2022-03-31 at 15 47 43" src="https://user-images.githubusercontent.com/210173/161070671-612b34db-3fad-4bb4-afe6-c38c8fc63e4f.png">

I don't get any similar logs on Firefox, but the site looks the same there too.

**Comment by verdverm** [comment]
@slafs Thanks for the report. I'm unable to reproduce this locally, however I did get one of the screenshot services to replicate on a desktop, but details are lacking there.

The font is supposed to be Roboto. It may be that your system does not have this font available? I will add it to the assets somewhere to ensure it is around. (thought that was the case but seemingly not...) Will reply to this issue once they are so you can verify if it resolves the issue.

Not sure about the blocked resource. I don't see any `data:font/truetype` resources loaded in my logs. Can you provide a screenshot of this or any other info? (maybe the preview of what it is supposed to be) ... Looks like it may be related to fontawsome assets and fallback? (but you have those rendering)
