### ISSUE TITLE
Rainbond using CUE

### ISSUE THREAD

**Issue by ZhangSetSail** [hofstadter-io/cuetorials.com#66]
Rainbond

Repository: https://github.com/goodrain/rainbond.git
website: https://www.rainbond.com/
Documentation: https://www.rainbond.com/docs/quick-start/get-start/

**Comment by verdverm** [comment]
Do you have an English version for your site? I have no idea what rainbond is

**Comment by ZhangSetSail** [comment]
> Do you have an English version for your site? I have no idea what rainbond is
Thank you for your reply. Regarding your question, I'm sorry that we don't have English documentation yet, but we will add it in the near future.
Rainbond is a cloud native multi cloud application management platform, which is easy to use and does not need to understand containers, kubernetes and underlying complex technologies. It supports the management of multiple kubernetes clusters and the management of the whole life cycle of enterprise applications. The main functions include application development environment, application market, micro service architecture, application delivery, application operation and maintenance, application level multi cloud management, etc.

**Comment by verdverm** [comment]
There is at least https://github.com/goodrain/rainbond/blob/main/README-en.md

It also seems that Google wants to translate the site automatically today

Do you have any links in your documentation to where CUE is used? (I can rely on translations, they seem sufficient for understanding)

**Comment by ZhangSetSail** [comment]
The use of CUE is not described in detail in the documentation, but the specific use can be found at https://github.com/goodrain/rainbond/blob/main/worker/appm/componentdefinition/thirdcomponentdefinition.go. Some of our recent changes will use CUE again. After an in-depth understanding, we will try to organize a CUE usage and add it to our official documentation.
